codecov:
  branch: main
  require_ci_to_pass: true

coverage:
  notify:
    slack:
      message: 'hello from codecov'
      default:
        url: secret:v2::6L1ovpYJry+OjhAfrUpBTkLLUmKjY2TrCQdlMY1oNuaK4PlK7xwnJftUsqQx+NYnNdqVbNDY0lD+VtylZx07Tyye//mYF4V265NrlhlwH6ui/TJ8l2RVe8eM9fDodDyzTlqXl4cf8aWU6W20nuQyXcSuEkpn6pwxfjK3HPN6Cb8=
        only_pulls: false

  status:
    project:
      default:
        informational: true
        target: auto
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%
    patch:
      default:
        informational: true

  range: 30..75
  round: up
  precision: 1

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,tree,betaprofiling,footer'
  behavior: default
  show_critical_paths: true
  require_changes: true

ignore:
  - 'build/'
  - 'dist/'
  - '.eslintrc.js'
  - 'jest.config.js'
  - 'prettier.config.js'
  - 'src/cli/index.ts'
  - 'src/index.ts'
