codecov:
  branch: main
  require_ci_to_pass: true

coverage:
  notify:
    slack:
      branches: main
      threshold: 10%
      url: '{CODECOV_SLACK_WEBHOOK_URL}'

  status:
    project:
      default:
        informational: true
        target: auto
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%
    patch:
      default:
        informational: true
  range: 30..75
  round: up
  precision: 1

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: true

ignore:
  - 'build/'
  - 'dist/'
  - '.eslintrc.js'
  - 'jest.config.js'
  - 'prettier.config.js'
  - 'src/cli/index.ts'
  - 'src/index.ts'
