name: Run Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
    branches:
      - main

  pull_request:

env:
  USE_CODECOV_SERVICE: yes

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Run the tests with coverage
        run: npm run test -- --passWithNoTests --coverage --coverageReporters json

      - name: Prepare codecov config
        run: |
          wget --quiet https://github.com/webdevops/go-replace/releases/download/22.10.0/go-replace.linux.amd64 -O /tmp/goreplace
          chmod +x /tmp/goreplace
          /tmp/goreplace -s '{CODECOV_SLACK_WEBHOOK_URL}' -r '${{ secrets.CODECOV_SLACK_WEBHOOK_URL }}' .github/codecov.yml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ success() && env.USE_CODECOV_SERVICE == 'yes' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
